### ISSUE TITLE
How to use this model?

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#1]
Could you please provide a more detailed description of the steps to use？

**Comment by ConsistencyVC** [comment]
1. Generate the PPG or WEO of the source speech in the [convert py file](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/467ed5e632b2b328d01c87cb73e92b26b36deb05/whisperconvert_exp.py#L39C1-L39C1)
2. Put the root of reference speech to [tgt](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/467ed5e632b2b328d01c87cb73e92b26b36deb05/whisperconvert_exp.py#L47)

**Comment by tppqt** [comment]
> * Generate the PPG or WEO of the source speech in the [convert py file](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/467ed5e632b2b328d01c87cb73e92b26b36deb05/whisperconvert_exp.py#L39C1-L39C1)
> * Put the root of reference speech to [tgt](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/467ed5e632b2b328d01c87cb73e92b26b36deb05/whisperconvert_exp.py#L47)

I encountered a new problem. After modifying the files in the 'src' and 'tgt' directories, I ran 'whisperconvert_exp.py' and received the following error message

![884C1CB129B3A909B2BBBB549B5718D5](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/63a75ced-214e-4f98-a479-3a1c8264baae)
![12](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/3eea3a3f-4156-46fb-8f83-b2cb468fda78)

How to solve this problem?

**Comment by ConsistencyVC** [comment]
You need to use preprocess_ppg.py to generate the qiwhisper.pt.npy first.  About how to use preprocess_ppg.py, you need to put your source wavs in a folder, then change this [line](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/b1de04598e36781337a3086c19c83229d8ee3ded/preprocess_ppg.py#L45)

**Comment by ConsistencyVC** [comment]
事实上确实是我的问题，我最近太忙了，加上天气太热，就懒得把这两个py文件整合在一起了
