### ISSUE TITLE
HiFiGAN not found

### ISSUE THREAD

**Issue by gandolfxu** [ConsistencyVC/ConsistencyVC-voive-conversion#10]
python whisperconvert_exp.py

Traceback (most recent call last):
  File "whisperconvert_exp.py", line 9, in <module>
    import utils
  File "/home/notebook/code/personal/ConsistencyVC-voive-conversion/utils.py", line 14, in <module>
    import hifigan
ModuleNotFoundError: No module named 'hifigan'

**Comment by tppqt** [comment]
use FreeVC's hifigan
![5](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/fa9fdbb3-daf5-445b-9fb4-9e7efbb8f57b)

**Comment by guoyingying432** [comment]
Actually there is no problem to just delete it. Because ConsistencyVC don't use hifigan directly. I will change the code maybe three hours later.

**Comment by ConsistencyVC** [comment]
I revised it, hope there is no bug this time
