### ISSUE TITLE
必须要运行10K个epoch吗

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#12]
用300条语音数据，微调了2200个epoch，发现转换后全是电流声，是语音数据太少了还是说是训练epoch少了

**Comment by ConsistencyVC** [comment]
对训练集中的语音，输出也是电流声吗，还是只是对测试用的语音输出是电流声。我记得你说原预训练模型对你的语音的输出是没有电流声的。可能是训练epoch多了，模型对这300条语音过拟合了。解决方法要么是减少训练epoch试一试，要么是把这300条语音混在大的语音数据集里。

**Comment by tppqt** [comment]
我试试看
