### ISSUE TITLE
Why is audio max duration is 29s? 

### ISSUE THREAD

**Issue by skol101** [ConsistencyVC/ConsistencyVC-voive-conversion#13]
Looking here I cannot help but notice https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/620266afe2432a2be9847400bbc920ed065c8dea/preprocess_ppg.py#L20 

What if source is longer than 29s? Should it be split by 29s duration, converted one-by-one, and the joined back?

**Comment by tppqt** [comment]
same question, How can I extend the running time, I change this line but get error
![4A7BFE80FB6E480AEF37B749D74B39BF](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/bc39bc56-4986-44e2-ad43-77d929061319)

**Comment by ConsistencyVC** [comment]
This is the problem of [Whisper...](https://github.com/openai/whisper)
![image](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/135992709/9d71a024-1784-4e78-afa9-4f47f8e95145)

So @skol101 you are right, it should be split by 29s duration, converted one-by-one, and then joined back

**Comment by skol101** [comment]
Understood. Thanks!

**Comment by ConsistencyVC** [comment]
Hello everyone, I make a simple change to the whisper convert py file, you can use [this file](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/83f72b0801240e7d932c9314431df6e75f2d1c22/whisperconvert_longaudio.py) to convert the long audio.
