### ISSUE TITLE
如果从头训练的话大概需要多长时间呢

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#14]
我用一张A100训练AIShell3，2天了才跑75个epoch，如果要达到预训练模型那种程度，必须要跑100K step才行吗，目前我好像66k step只能听到电流声，一点语音都没有
![321](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/b682fd0a-1441-4461-8a63-3126f691688c)

**Comment by ConsistencyVC** [comment]
咋搞的。。。你config和train.log发我邮箱看看，3245016476@qq.com，顺便一提，你的loss全变成nan了，应该是梯度爆炸了，

**Comment by ConsistencyVC** [comment]
你从头开始训练时候，把speaker consistency loss注释掉了吗

**Comment by tppqt** [comment]
发你邮箱了
