### ISSUE TITLE
Can fine-tuned model be fine-tuned again? 

### ISSUE THREAD

**Issue by skol101** [ConsistencyVC/ConsistencyVC-voive-conversion#15]
In order to fine tune on a new additional dataset , could the trained model be fine-tuned without unlearning on the previous data? 

Can this fine tuned model be further fined tuned on a new set of data ?

**Comment by ConsistencyVC** [comment]
I think there is no problem to fine tune it, the data used to train this model is simple 16KHz wav.  By the way, is there any problem to train from the start?
