### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by gandolfxu** [ConsistencyVC/ConsistencyVC-voive-conversion#16]
Do you have a plan?

**Comment by ConsistencyVC** [comment]
I only have one GPU... if anyone can help me to write the code the support the multi GPU, I will be very grateful.

**Comment by thivux** [comment]
the code is based on vits repo, so you can take a look at that repo to see how distributed training is implemented. almost all you need is to uncomment the code related to distributed training, which is already there.
