### ISSUE TITLE
XVC Performance on A2M/A2A

### ISSUE THREAD

**Issue by tarepan** [ConsistencyVC/ConsistencyVC-voive-conversion#17]
## Summary
Is the XVC model evaluated with Any-to setup in the paper?  
If not, have you ever try it?  

## Current Status
The paper said that XVC is evaluated for unseen *reference* (target) speakers.  

> These unseen speaker samples were used to evaluate the ability of the model to imitate speakers not present in the training set.  

This means that the XVC model is evaluated with to-Many (seen) and to-Any (unseen) setup in the paper.  

At the same time, Whisper can be used for unseen *source* speakers, so it can be evaluated with Many-to and/or Any-to setup.  
But there seems to be no description about *source* speaker's seen/unseen characteristics.  

## Quiestion
I have two quiestion.  

1. In the paper, Is the XVC model evaluated with Any-to or Many-to?
2. If Many-to, have you ever try A2M setup? (like QuickVC)

### Notes
Thanks for the great work!  
I am excited to see this big advances in non-traditional VC area.

**Comment by ConsistencyVC** [comment]
In the paper, Is the XVC model evaluated with Any-to or Many-to?
In the paper, it isn't

If Many-to, have you ever try A2M setup? (like QuickVC)
Yes, and the result is still good.

Why not just try the pretrained model? The environment setup is similar to quickvc.

**Comment by tarepan** [comment]
Thanks for the answer!

I tried your pretrained model with few private unseen speakers, and got good results.  
I am relieved to hear that official ConsistencyVC team got good results in A2M setup.
