### ISSUE TITLE
Info about ConsistencyEVC and ConsistencyEVC-whisper

### ISSUE THREAD

**Issue by MikeMill789** [ConsistencyVC/ConsistencyVC-voive-conversion#19]
Hey , great work and thanks for making it available to all of us. I have few doubts regarding these models :

1) why do you think performance of ConsistencyEVC is slightly better than ConsistencyEVC-whisper (atleast in the demo)?

2) How many steps did you train these models for ?
3) What dataset is used for the training? ( Is it only ESD or ESD combined with VCTK) ?

**Comment by ConsistencyVC** [comment]
1. Because they use different content feature. For the EVC task, PPG is better than whisper
2. About 300k steps
3. Yes, for the EVC only ESD-ENG combined with VCTK

**Comment by MikeMill789** [comment]
Thanks for the reply. I think ConsistencyEVC-whisper is also retaining some expression information from source speech along with content information. Do you think it would help if we reduce the size of bottleneck vector further down from 192 (to force it to only learn content features) and start training again.

**Comment by MikeMill789** [comment]
Also I see this code commented down in train.py
`model_name = 'audeering/wav2vec2-large-robust-12-ft-emotion-msp-dim'`
`processor = Wav2Vec2Processor.from_pretrained(model_name)`
Have you tried using this pretrained emotional embedding like freevc (not freevc-s) has pretrained speaker embedding? If not , why didn't you go down that route after considering it ?

**Comment by ConsistencyVC** [comment]
> Thanks for the reply. I think ConsistencyEVC-whisper is also retaining some expression information from source speech along with content information. Do you think it would help if we reduce the size of bottleneck vector further down from 192 (to force it to only learn content features) and start training again.

You can try but I have no expectations of removing emotional messages

**Comment by ConsistencyVC** [comment]
> Also I see this code commented down in train.py `model_name = 'audeering/wav2vec2-large-robust-12-ft-emotion-msp-dim'` `processor = Wav2Vec2Processor.from_pretrained(model_name)` Have you tried using this pretrained emotional embedding like freevc (not freevc-s) has pretrained speaker embedding? If not , why didn't you go down that route after considering it ?

Because the emotion clone ability is not good enough

**Comment by MikeMill789** [comment]
Cool , thanks .
