### ISSUE TITLE
Comparisons of N-MOS and S-MOS: this vs QuickVC

### ISSUE THREAD

**Issue by skol101** [ConsistencyVC/ConsistencyVC-voive-conversion#4]
I wonder if you have already have data on this?

**Comment by ConsistencyVC** [comment]
Sorry, I don't compare them because they use different datasets and face different tasks. What I'm sure is ConsistencyXVC is better than QuickVC in terms of cross-lingual voice conversion, and ConsistencyEVC is better in terms of expressive voice conversion.
