### ISSUE TITLE
I can't find the directory of cvc-whispers-three

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#5]
这个文件夹里面有什么？应该是什么样的格式的

**Comment by tppqt** [comment]
是不是按照freeVC先下采样，然后再做这几步啊
![Uploading 2AA667B6-6A67-4297-8DC6-50955C4312A5.png…]()

**Comment by tppqt** [comment]
是不是按照freeVC先下采样，然后再做这几步啊
![2AA667B6-6A67-4297-8DC6-50955C4312A5](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/e4efa3e3-254a-426e-b6cb-309b993954a5)

**Comment by ConsistencyVC** [comment]
预处理就两步：把语音下采样到16khz存在一个文件夹里，之后用preprocess_ppg.py给每个语音生成对应的内容特征；
cvc-whispers-three这个文件夹是用来保存训练好的模型的，要是想在预训练的模型的基础上训练，就把[训练好的模型](https://drive.google.com/drive/folders/1wRBoCbCHSXpSmGZhg8LbxlcLa3L26ig0?usp=drive_link)放进去就行了

**Comment by ConsistencyVC** [comment]
这个文件夹使用了
