### ISSUE TITLE
Accent removal + voice cloning

### ISSUE THREAD

**Issue by oijoijcoiejoijce** [ConsistencyVC/ConsistencyVC-voive-conversion#6]
Thanks for the great work - a bit confused on how to run this to have the voice and accent of speaker A transfered into the speech of speaker B. Can you provide guidance on that please?

**Comment by ConsistencyVC** [comment]
Sorry, I'm a little confused, the generated speech's accent is the original speaker, who is a native speaker; the speaker is the target speaker.
Or, we can say: speaker A is the original speaker, B is the target speaker, the output speech will be speaker B with speaker A's accent.
