### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#7]
按照你说的步骤我尝试复现微调，先添加了train.txt和test.txt(少量数据)
![QQ20230714-0](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/6cff9987-266d-4599-9983-57ec179761e2)
![2F932491E2E249860FE88BD2FB996FCD](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/3ccd8038-3563-4975-ac1d-08b85158ef70)
然后我用preprocess_ppg.py都预处理了
![1](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/0c4c6025-252f-48f5-a5f6-a86d96ca4019)
然后我再按照步骤修改了步骤1，再运行步骤2
![2](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/662273ca-3bfe-4522-88ad-edd30193ad70)
结果就报这个错了
![5AB8020573B46B4E3EFBF81662D3E78D](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/c3d5b1e8-f188-4ead-b0f2-cb946d56f93f)

**Comment by guoyingying432** [comment]
可能是数据集数量小于batch size导致的，把config里的batch size设置成2之后试试

**Comment by tppqt** [comment]
> 可能是数据集数量小于batch size导致的，把config里的batch size设置成2之后试试
改了还是不行呢


![3](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/76574d69-7e9f-4cc6-a05c-6f60dcc00567)

**Comment by ConsistencyVC** [comment]
找到错误了，图片里的红框圈出来的那个0：
![253514803-76574d69-7e9f-4cc6-a05c-6f60dcc00567](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/135992709/fff1e28c-495d-4480-a69e-4ece034a4f9f)

改[这一行](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/blob/8067940d7ab794bff1a085c879e0436246810a5a/train_whisper_emo.py#L71)，比如删掉”75，“，直到0不出现

**Comment by tppqt** [comment]
我试试

**Comment by ConsistencyVC** [comment]
75对应的语音长度就是一秒半，估计是因为你数据集里的语音都是大于一秒半的

**Comment by Rakshith12-pixel** [comment]
Hi, I am facing the same issue, not during finetuning on a large dataset with many spkeaers, but on a single speaker.Can you please tell me whats the solution?
@ConsistencyVC
