### ISSUE TITLE
Uploaded model mistake

### ISSUE THREAD

**Issue by gandolfxu** [ConsistencyVC/ConsistencyVC-voive-conversion#8]
The checkpoint sunder cvc-whispers-three-emo-loss are not right!

**Comment by ConsistencyVC** [comment]
Sorry, can you explain what happened, which one is not right?

**Comment by gandolfxu** [comment]
In the file whisperconvert_exp.py, the checkpoint name do not match that in the gdriver. Instead the checkpoint name of XVC and EVC are the same.

`parser = argparse.ArgumentParser()
    parser.add_argument("--hpfile", type=str, default="./logs/cvc-whispers-three-emo-loss/config.json", help="path to json config file")
    parser.add_argument("--ptfile", type=str, default="./logs/cvc-whispers-three-emo-loss/G_cvc-whispers-three-emo-loss.pth", help="path to pth file")
    parser.add_argument("--outdir", type=str, default="output/60_exp_crosslingual_whispers-three-emo-loss", help="path to output dir")`

![Image_20230714162326](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/50284410/6624222f-68bf-4411-bc84-faeb3215fa08)

**Comment by ConsistencyVC** [comment]
ummm...I rename it wrong. But actually the checkpoint is right, just rename it is OK. I will revise it.

**Comment by ConsistencyVC** [comment]
Ok, I renamed it, if there is still any problem, just contact me

**Comment by Fritskee** [comment]
@ConsistencyVC When is the D_cvc model used actually? When I swap the models in `whisperconvert_exp` to the `D_cvc` model, it complains that the config is incorrect

**Comment by ConsistencyVC** [comment]
> @ConsistencyVC When is the D_cvc model used actually? When I swap the models in `whisperconvert_exp` to the `D_cvc` model, it complains that the config is incorrect

That is the discriminator...
