### ISSUE TITLE
我如果想微调的话，是操作哪一步呢

### ISSUE THREAD

**Issue by tppqt** [ConsistencyVC/ConsistencyVC-voive-conversion#9]
就是我现在能跑起来了，想加一种音色进去，我应该从1开始运行，还是从2开始运行啊
![4](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion/assets/19279148/46c59b4a-8a68-4a44-932e-f6da0f388faf)
1和2都是在cvc-whispers-three下的预训练模型下进行调整？还是1是重新开始训练，2是在原有的模型上微调，有点迷茫

**Comment by ConsistencyVC** [comment]
直接在预训练模型上微调比较好，从2开始

**Comment by tppqt** [comment]
好的，Thanks♪(･ω･)ﾉ
